// Copyright 2002 Henrik Lauritzen.
/*
    This file is part of the AgentC Toolkit.

    The AgentC Toolkit is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The AgentC Toolkit is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the AgentC Toolkit.  If not, see <http://www.gnu.org/licenses/>.
*/
/* Generated By:JavaCC: Do not edit this line. AgentCparserConstants.java */
package dk.dtu.imm.cse.agent.act.acc;

public interface AgentCparserConstants {

  int EOF = 0;
  int IDENTIFIER = 4;
  int IDENTIFIERSTART = 5;
  int LETTER = 6;
  int DIGIT = 7;
  int VARIABLE = 8;
  int ATTITUDE = 9;
  int INTEGER_LITERAL = 10;
  int DOUBLE_LITERAL = 11;
  int EXPONENT = 12;
  int STRING_LITERAL = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "<IDENTIFIER>",
    "<IDENTIFIERSTART>",
    "<LETTER>",
    "<DIGIT>",
    "<VARIABLE>",
    "<ATTITUDE>",
    "<INTEGER_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"ATTITUDES\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\"DEFS\"",
    "\"FACTS\"",
    "\"PROCEDURE\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"=\"",
    "\"WHEN\"",
    "\"[\"",
    "\"]\"",
    "\"NOTHING\"",
    "\"AS\"",
    "\"ADOPT\"",
    "\"DROP\"",
    "\"SAY\"",
    "\"LET\"",
    "\"LOCKED\"",
    "\"RETURN\"",
    "\"CALL\"",
    "\"IF\"",
    "\"ELSIF\"",
    "\"ELSE\"",
    "\"DO\"",
    "\"XEQ\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"SELF\"",
    "\"Q\"",
  };

}
